### ISSUE TITLE
[SUGGESTION] Soldiers upgrades

### ISSUE THREAD

**Issue by JukoiDev** [matthewperiut/Clay-Soldiers#1]
Hey! I've been thinking about how the upgrades could be coded. I think we could add new NBT field to the Doll entity.  So the NBT tags for the soldier entity would look like this:
```
{
  "upgrades": {"diamond_crown": "core", "stick_sword": "main_hand", "stick_sword": "off_hand"},
  ( ETC. )
}
```
Then the entity would just look for the items in it's sight and pick up them. You get the idea, right?
P.S. I am very glad you ported Clay Soldiers to the 1.19.3! Thanks

**Comment by JukoiDev** [comment]
Another quite nice feature would be that soldier's equipment would stay after he died, and to reset it, the player would have to place a clay doll in a crafting slot.

**Comment by JukoiDev** [comment]
I will try to make equipment now, by myself using addAdditionalSaveData and readAdditionalSaveData methods

**Comment by matthewperiut** [comment]
I just saw this this issue that you made, and honestly I'm busy with other things specifically lots of college and work, so I'll be completely happy to merge a good pr! I was planning to do this, but I enjoy the NBT format you laid out. I wish you luck, and thanks for your efforts! If it doesn't work out and you get busy, I'll get around to attempting an implementation like this.

**Comment by JukoiDev** [comment]
Oh, sure! Thanks

**Comment by JukoiDev** [comment]
this is gonna be some form of a challenge, because i've never used yarn mappings
