### ISSUE TITLE
Game crashes when trying to spawn clay soldiers

### ISSUE THREAD

**Issue by GregTheChief** [matthewperiut/Clay-Soldiers#3]
Here is the crash report:
_The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: 'software.bernie.geckolib3.core.manager.AnimationFactory software.bernie.geckolib3.util.GeckoLibUtil.createFactory(software.bernie.geckolib3.core.IAnimatable)'_
Any idea whats happening here?

**Comment by matthewperiut** [comment]
Try installing geckolib for your version of Minecraft and mod loader! That's what the error is saying

**Comment by JukoiDev** [comment]
Looks like the either Geckolib is missing(this should be noted by the modloader!) or you are using older(possibly newer) version of Geckolib that is recommended.

**Comment by GregTheChief** [comment]
I use geckolib 3.1.21, which is the version it recommends when I start the game without geckolib :/

**Comment by matthewperiut** [comment]
Is this 1.19.3? Because they changed to a new geckolib, and maybe I forgot to change fabric info bc I literally moved the code to geckolib 4

**Comment by GregTheChief** [comment]
No I use 1.19.2

**Comment by matthewperiut** [comment]
Can you send the complete crash log?

**Comment by GregTheChief** [comment]
[crash-2023-01-12_21.52.12-server.txt](https://github.com/matthewperiut/Clay-Soldiers/files/10405873/crash-2023-01-12_21.52.12-server.txt)

**Comment by GregTheChief** [comment]
was the crashlog helpful? :/

**Comment by matthewperiut** [comment]
I'm still taking a look, gonna try to reproduce

**Comment by matthewperiut** [comment]
Alright, I've discovered the issue. The recommended version of geckolib described my forge by using my mod info file is wrong. It's an old version now, so I'm not going to go back and fix it, because this is a relatively small mod, and we're moving on from that version.

Anyways, the fix is simple. Install a new geckolib3 version, like 3.1.36 or newer. I tested 3.1.38, and it worked great, the link to the download is here:  https://www.curseforge.com/minecraft/mc-mods/geckolib/files/4096661

Comment if this doesn't work for you but it fixed the issue on my end!

**Comment by GregTheChief** [comment]
IT WORKS! thanks :)

**Comment by Leb0** [comment]
> Alright, I've discovered the issue. The recommended version of geckolib described my forge by using my mod info file is wrong. It's an old version now, so I'm not going to go back and fix it, because this is a relatively small mod, and we're moving on from that version.
> 
> Anyways, the fix is simple. Install a new geckolib3 version, like 3.1.36 or newer. I tested 3.1.38, and it worked great, the link to the download is here: https://www.curseforge.com/minecraft/mc-mods/geckolib/files/4096661
> 
> Comment if this doesn't work for you but it fixed the issue on my end!

Hey, do you have a file for fabric? 
, it happened the same for me.
