### ISSUE TITLE
[suggestion] make clay soldiers spawn naturally

### ISSUE THREAD

**Issue by MoreCaveSounds** [matthewperiut/Clay-Soldiers#6]
title

**Comment by matthewperiut** [comment]
I wouldn't like to make this addition, because it conflicts with another thing which is that they don't despawn. They don't despawn because some people like to keep the clay soldiers around. Unfortunately, this wouldn't work, because they couldn't despawn.

**Comment by MoreCaveSounds** [comment]
> I wouldn't like to make this addition, because it conflicts with another thing which is that they don't despawn. They don't despawn because some people like to keep the clay soldiers around. Unfortunately, this wouldn't work, because they couldn't despawn.

damn that sucks... a workaround for this could be to just add configs for them to spawn naturally and to despawn or not

**Comment by TrustNoOneElse** [comment]
> > I wouldn't like to make this addition, because it conflicts with another thing which is that they don't despawn. They don't despawn because some people like to keep the clay soldiers around. Unfortunately, this wouldn't work, because they couldn't despawn.
> 
> damn that sucks... a workaround for this could be to just add configs for them to spawn naturally and to despawn or not

We can make it easier, i built a mixin which can get the spawn reason, then we can simply say, when its created per spawn_egg (Player) never despawn or when its generated trough world_generation/spawner as example it can despawn. I will implement this, as i saw many wished for that :) For now i will only prepare it, because i think the base features (Upgrades) are more important

**Comment by memphismc** [comment]
> > > I wouldn't like to make this addition, because it conflicts with another thing which is that they don't despawn. They don't despawn because some people like to keep the clay soldiers around. Unfortunately, this wouldn't work, because they couldn't despawn.
> > 
> > 
> > damn that sucks... a workaround for this could be to just add configs for them to spawn naturally and to despawn or not
> 
> We can make it easier, i built a mixin which can get the spawn reason, then we can simply say, when its created per spawn_egg (Player) never despawn or when its generated trough world_generation/spawner as example it can despawn. I will implement this, as i saw many wished for that :) For now i will only prepare it, because i think the base features (Upgrades) are more important

awesome! ill follow the mod for updates, naturally spawning clay soldiers will be really fun

**Comment by TrustNoOneElse** [comment]
> 
> awesome! ill follow the mod for updates, naturally spawning clay soldiers will be really fun

I think so too, when they spawn later with random upgrades or maybe even in some generated clay cities ^^ But for that i hope that the author of this mod, will grant me permissions, otherwise it was all done for nothing since this mod is all rights reserved from the licence :D

**Comment by memphismc** [comment]
> > awesome! ill follow the mod for updates, naturally spawning clay soldiers will be really fun
> 
> I think so too, when they spawn later with random upgrades or maybe even in some generated clay cities ^^ But for that i hope that the author of this mod, will grant me permissions, otherwise it was all done for nothing since this mod is all rights reserved from the licence :D

you can just dm me the build on discord 😏

**Comment by TrustNoOneElse** [comment]
>
> you can just dm me the build on discord 😏

That would also count as distribution and would be against this license as long as he don't change it. I mean he is still active, so i hope he will answer soon..

**Comment by memphismc** [comment]
> > you can just dm me the build on discord 😏
> 
> That would also count as distribution and would be against this license as long as he don't change it. I mean he is still active, so i hope he will answer soon..

ah, i thought as long as i dont share it and keep it only for personal use it was ok, i still dont know for sure what each of these licenses mean

**Comment by matthewperiut** [comment]
Feel free to send the modified mod to memphis, but I would also gladly merge your contributions! I don't know if I said this but I'm a college senior so I'm not really that active on this
