### ISSUE TITLE
Maintaining Request | Continuing Development?

### ISSUE THREAD

**Issue by TrustNoOneElse** [matthewperiut/Clay-Soldiers#7]
Hey there,

are there any plans to get this further? :) Im a huge fan of the clay soldier mod and would personally like to contribute to it/work together, help to maintain it or maintain it myself if you grant the permissions. 

Best regards,
Florian

**Comment by matthewperiut** [comment]
Hi feel free to write up some code and make a PR and I'd love to add you to the modrinth/curseforge page if it's good work! Right now I'm waiting for neoforge to stabilize and fortified fabric api to update to 1.20.4 because it would ease development for me

**Comment by TrustNoOneElse** [comment]
> Hi feel free to write up some code and make a PR and I'd love to add you to the modrinth/curseforge page if it's good work! Right now I'm waiting for neoforge to stabilize and fortified fabric api to update to 1.20.4 because it would ease development for me

Sounds fair to me! Im currently extending the AI goals to support tracking and finding things easier. 

Im kinda curios, why would it ease development for you? 

Afterwards i will try to add the upgrade system.

What i have done so far is
- adding bones for the hand
- mixin to get the spawn reason of a mob
- make the soldiers able to hold a stick

Which PR pattern would best fit for you? All in one or feature based?

If you want to exchange informations my discord name is: trustnooneelse

**Comment by matthewperiut** [comment]
I’m a fabric shill is all, forge is not my favorite api so if I had fabric api basically I’d be enjoying that

**Comment by memphismc** [comment]
new maintainer confirmed? :0

**Comment by TrustNoOneElse** [comment]
> new maintainer confirmed? :0
> 
> speaking of maintaining, will fabric 1.20.1 continue to be supported?

Additional yes :) 

I will further test and develop against 1.20.1 forge and fabric yes. How we handle it when matthew is back, we will see then (like backporting and so on) :)

If you have any further ideas or questions, feel free to open a issue here :) I will resolve this one now!

My productive times will be mostly on the weekends, for now its a little bit stopped trough some privat problems since saturday, but they should be resolved in the beginning of the next week! :)
